import re

# Input data as a dictionary with player names and their URLs
player_data = {
    "David Warner": "https://www.espncricinfo.com/cricketers/david-warner-219889",
    "Marnus Labuschagne": "https://www.espncricinfo.com/cricketers/marnus-labuschagne-787987",
    "Steve Smith": "https://www.espncricinfo.com/cricketers/steve-smith-7656",
    "Usman Khawaja": "https://www.espncricinfo.com/cricketers/usman-khawaja-215155",
    "Travis Head": "https://www.espncricinfo.com/cricketers/travis-head-530011",
    "Cameron Green": "https://www.espncricinfo.com/cricketers/cameron-green-13845",
    "Alex Carey": "https://www.espncricinfo.com/cricketers/alex-carey-326434",
    "Mitchell Starc": "https://www.espncricinfo.com/cricketers/mitchell-starc-311592",
    "Nathan Lyon": "https://www.espncricinfo.com/cricketers/nathan-lyon-272279",
    "Josh Hazlewood": "https://www.espncricinfo.com/cricketers/josh-hazlewood-288284",
    "Rohit Sharma": "https://www.espncricinfo.com/cricketers/rohit-sharma-25963",
    "Shubman Gill": "https://www.espncricinfo.com/cricketers/shubman-gill-1070173",
    "Cheteshwar Pujara": "https://www.espncricinfo.com/cricketers/cheteshwar-pujara-32540",
    "Virat Kohli": "https://www.espncricinfo.com/cricketers/virat-kohli-253802",
    "Ajinkya Rahane": "https://www.espncricinfo.com/cricketers/ajinkya-rahane-277916",
    "Ravindra Jadeja": "https://www.espncricinfo.com/cricketers/ravindra-jadeja-234675",
    "Rishabh Pant": "https://www.espncricinfo.com/cricketers/rishabh-pant-931581",
    "Ravichandran Ashwin": "https://www.espncricinfo.com/cricketers/ravichandran-ashwin-26421",
    "Mohammed Shami": "https://www.espncricinfo.com/cricketers/mohammed-shami-481896",
    "Jasprit Bumrah": "https://www.espncricinfo.com/cricketers/jasprit-bumrah-625383",
    "Mohammed Siraj": "https://www.espncricinfo.com/cricketers/mohammed-siraj-940973",
    "Dean Elgar": "https://www.espncricinfo.com/cricketers/dean-elgar-230852",
    "Aiden Markram": "https://www.espncricinfo.com/cricketers/aiden-markram-600498",
    "Rassie van der Dussen": "https://www.espncricinfo.com/cricketers/rassie-van-der-dussen-337790",
    "Temba Bavuma": "https://www.espncricinfo.com/cricketers/temba-bavuma-372116",
    "Quinton de Kock": "https://www.espncricinfo.com/cricketers/quinton-de-kock-379143",
    "Keshav Maharaj": "https://www.espncricinfo.com/cricketers/keshav-maharaj-267724",
    "Kagiso Rabada": "https://www.espncricinfo.com/cricketers/kagiso-rabada-550215",
    "Anrich Nortje": "https://www.espncricinfo.com/cricketers/anrich-nortje-481979",
    "Lungi Ngidi": "https://www.espncricinfo.com/cricketers/lungi-ngidi-542023",
    "Marco Jansen": "https://www.espncricinfo.com/cricketers/marco-jansen-696401",
    "Wiaan Mulder": "https://www.espncricinfo.com/cricketers/wiaan-mulder-698189",
    "Ben Stokes": "https://www.espncricinfo.com/cricketers/ben-stokes-311158",
    "Zak Crawley": "https://www.espncricinfo.com/cricketers/zak-crawley-665053",
    "Ben Duckett": "https://www.espncricinfo.com/cricketers/ben-duckett-521637",
    "Joe Root": "https://www.espncricinfo.com/cricketers/joe-root-303669",
    "Harry Brook": "https://www.espncricinfo.com/cricketers/harry-brook-911707",
    "Jonny Bairstow": "https://www.espncricinfo.com/cricketers/jonny-bairstow-297433",
    "Moeen Ali": "https://www.espncricinfo.com/cricketers/moeen-ali-8917",
    "Chris Woakes": "https://www.espncricinfo.com/cricketers/chris-woakes-247235",
    "Stuart Broad": "https://www.espncricinfo.com/cricketers/stuart-broad-10617",
    "James Anderson": "https://www.espncricinfo.com/cricketers/james-anderson-8608",
    "Ollie Robinson": "https://www.espncricinfo.com/cricketers/ollie-robinson-527776",
    "Kane Williamson": "https://www.espncricinfo.com/cricketers/kane-williamson-277906",
    "Tom Latham": "https://www.espncricinfo.com/cricketers/tom-latham-388802",
    "Devon Conway": "https://www.espncricinfo.com/cricketers/devon-conway-379140",
    "Henry Nicholls": "https://www.espncricinfo.com/cricketers/henry-nicholls-539511",
    "Daryl Mitchell": "https://www.espncricinfo.com/cricketers/daryl-mitchell-17970",
    "Tom Blundell": "https://www.espncricinfo.com/cricketers/tom-blundell-440516",
    "Colin de Grandhomme": "https://www.espncricinfo.com/cricketers/colin-de-grandhomme-55395",
    "Tim Southee": "https://www.espncricinfo.com/cricketers/tim-southee-232364",
    "Trent Boult": "https://www.espncricinfo.com/cricketers/trent-boult-277912",
    "Neil Wagner": "https://www.espncricinfo.com/cricketers/neil-wagner-233713",
    "Matt Henry": "https://www.espncricinfo.com/cricketers/matt-henry-506612",
    "Dimuth Karunaratne": "https://www.espncricinfo.com/cricketers/dimuth-karunaratne-227772",
    "Pathum Nissanka": "https://www.espncricinfo.com/cricketers/pathum-nissanka-1028655",
    "Kusal Mendis": "https://www.espncricinfo.com/cricketers/kusal-mendis-629074",
    "Angelo Mathews": "https://www.espncricinfo.com/cricketers/angelo-mathews-49764",
    "Dhananjaya de Silva": "https://www.espncricinfo.com/cricketers/dhananjaya-de-silva-465793",
    "Dinesh Chandimal": "https://www.espncricinfo.com/cricketers/dinesh-chandimal-300628",
    "Ramesh Mendis": "https://www.espncricinfo.com/cricketers/ramesh-mendis-629084",
    "Lasith Embuldeniya": "https://www.espncricinfo.com/cricketers/lasith-embuldeniya-848109",
    "Suranga Lakmal": "https://www.espncricinfo.com/cricketers/suranga-lakmal-appuhami-48143",
    "Lahiru Kumara": "https://www.espncricinfo.com/cricketers/lahiru-kumara-784375",
    "Vishwa Fernando": "https://www.espncricinfo.com/cricketers/vishwa-fernando-465783",
    "Babar Azam": "https://www.espncricinfo.com/cricketers/babar-azam-348144",
    "Abdullah Shafique": "https://www.espncricinfo.com/cricketers/abdullah-shafique-922941",
    "Azhar Ali": "https://www.espncricinfo.com/cricketers/azhar-ali-39037",
    "Fawad Alam": "https://www.espncricinfo.com/cricketers/fawad-alam-40250",
    "Mohammad Rizwan": "https://www.espncricinfo.com/cricketers/mohammad-rizwan-41472",
    "Faheem Ashraf": "https://www.espncricinfo.com/cricketers/faheem-ashraf-681117",
    "Hasan Ali": "https://www.espncricinfo.com/cricketers/hasan-ali-29476",
    "Naseem Shah": "https://www.espncricinfo.com/cricketers/naseem-shah-1158088",
    "Yasir Shah": "https://www.espncricinfo.com/cricketers/yasir-shah-43685",
    "Kraigg Brathwaite": "https://www.espncricinfo.com/cricketers/kraigg-brathwaite-348024",
    "John Campbell": "https://www.espncricinfo.com/cricketers/john-campbell-23618",
    "Nkrumah Bonner": "https://www.espncricinfo.com/cricketers/nkrumah-bonner-314650",
    "Shai Hope": "https://www.espncricinfo.com/cricketers/shai-hope-581379",
    "Jason Holder": "https://www.espncricinfo.com/cricketers/jason-holder-391485",
    "Kyle Mayers": "https://www.espncricinfo.com/cricketers/kyle-mayers-348056",
    "Kemar Roach": "https://www.espncricinfo.com/cricketers/kemar-roach-230553",
    "Alzarri Joseph": "https://www.espncricinfo.com/cricketers/alzarri-joseph-670031",
    "Shannon Gabriel": "https://www.espncricinfo.com/cricketers/shannon-gabriel-446101",
    "Jomel Warrican": "https://www.espncricinfo.com/cricketers/jomel-warrican-432214",
    "Roston Chase": "https://www.espncricinfo.com/cricketers/roston-chase-391832",
    "Mominul Haque": "https://www.espncricinfo.com/cricketers/mominul-haque-373696",
    "Tamim Iqbal": "https://www.espncricinfo.com/cricketers/tamim-iqbal-56194",
    "Mushfiqur Rahim": "https://www.espncricinfo.com/cricketers/mushfiqur-rahim-56029",
    "Shakib Al Hasan": "https://www.espncricinfo.com/cricketers/shakib-al-hasan-56143",
    "Mehidy Hasan Miraz": "https://www.espncricinfo.com/cricketers/mehidy-hasan-miraz-629063",
    "Taskin Ahmed": "https://www.espncricinfo.com/cricketers/taskin-ahmed-538506",
    "Mustafizur Rahman": "https://www.espncricinfo.com/cricketers/mustafizur-rahman-330902",
    "Shoriful Islam": "https://www.espncricinfo.com/cricketers/shoriful-islam-990039",
    "Ebadot Hossain": "https://www.espncricinfo.com/cricketers/ebadot-hossain-932355",
    "Taijul Islam": "https://www.espncricinfo.com/cricketers/taijul-islam-401057",
    "Paul Stirling": "https://www.espncricinfo.com/cricketers/paul-stirling-303427",
    "Harry Tector": "https://www.espncricinfo.com/cricketers/harry-tector-961407",
    "George Dockrell": "https://www.espncricinfo.com/cricketers/george-dockrell-348034",
    "Lorcan Tucker": "https://www.espncricinfo.com/cricketers/lorcan-tucker-928057",
    "Mark Adair": "https://www.espncricinfo.com/cricketers/mark-adair-526441",
    "Barry McCarthy": "https://www.espncricinfo.com/cricketers/barry-mccarthy-348059",
    "Andy McBrine": "https://www.espncricinfo.com/cricketers/andy-mcbrine-417381",
    "Craig Young": "https://www.espncricinfo.com/cricketers/craig-young-364343",
    "Hashmatullah Shahidi": "https://www.espncricinfo.com/cricketers/hashmatullah-shahidi-440970",
    "Rahmat Shah": "https://www.espncricinfo.com/cricketers/rahmat-shah-533956",
    "Ikram Alikhil": "https://www.espncricinfo.com/cricketers/ikram-alikhil-935553",
    "Afsar Zazai": "https://www.espncricinfo.com/cricketers/afsar-zazai-420402",
    "Riaz Hassan": "https://www.espncricinfo.com/cricketers/riaz-hassan-1061090",
    "Sediqullah Atal": "https://www.espncricinfo.com/cricketers/sediqullah-atal-1161050",
    "Abdul Malik": "https://www.espncricinfo.com/cricketers/abdul-malik-39364",
    "Ismat Alam": "https://www.espncricinfo.com/cricketers/ismat-alam-1094444",
    "Azmatullah Omarzai": "https://www.espncricinfo.com/cricketers/azmatullah-omarzai-819429",
    "Zahir Khan": "https://www.espncricinfo.com/cricketers/zahir-khan-712219",
    "Zahir Shehzad": "https://www.espncricinfo.com/cricketers/zahir-shehzad-633397",
    "Rashid Khan": "https://www.espncricinfo.com/cricketers/rashid-khan-25923",
    "Yamin Ahmadzai": "https://www.espncricinfo.com/cricketers/yamin-ahmadzai-440968",
    "Naveed Zadran": "https://www.espncricinfo.com/cricketers/naveed-zadran-1276921",
    "Rakep Patel": "https://www.espncricinfo.com/cricketers/rakep-patel-267455",
    "Irfan Karim": "https://www.espncricinfo.com/cricketers/irfan-karim-348016",
    "Shem Ngoche": "https://www.espncricinfo.com/cricketers/shem-ngoche-308515",
    "Dhiren Gondaria": "https://www.espncricinfo.com/cricketers/dhiren-gondaria-529349",
    "Peter Langat": "https://www.espncricinfo.com/cricketers/peter-langat-578785",
    "Sachin Bhudia": "https://www.espncricinfo.com/cricketers/sachin-bhudia-1107656",
    "Vraj Patel": "https://www.espncricinfo.com/cricketers/vraj-patel-1178080",
    "Pushkar Sharma": "https://www.espncricinfo.com/cricketers/pushkar-sharma-1342166",
    "Neil Mugabe": "https://www.espncricinfo.com/cricketers/neil-mugabe-594321",
    "Sachin Gill": "https://www.espncricinfo.com/cricketers/sachin-gill-1342172"
}

# Function to transform the URLs
def transform_urls(player_data):
    transformed_urls = {}
    
    for player, url in player_data.items():
        # Extract the player ID using regex
        match = re.search(r"-(\d+)$", url)
        if match:
            player_id = match.group(1)
            # Create the new URL
            new_url = f"https://stats.espncricinfo.com/ci/engine/player/{player_id}.html?class=1;template=results;type=allround;wrappertype=print"
            transformed_urls[player] = new_url
    
    return transformed_urls

# Transform the URLs
new_urls = transform_urls(player_data)

# Print the transformed URLs
for player, url in new_urls.items():
    print(f"{player}: {url}")